from abc import ABC, abstractmethod

from app.shared.domain.value_objects import Email
from app.contexts.athletes.domain.student import Student


class StudentRepository(ABC):
    @abstractmethod
    def add(self, student: Student) -> None: ...
    @abstractmethod
    def get(self, student_id: str) -> Student | None: ...
    @abstractmethod
    def list_by_school(self, school_id: str) -> list[Student]: ...
    @abstractmethod
    def list_by_guardian_email(self, email: Email) -> list[Student]: ...
    @abstractmethod
    def remove(self, student: Student) -> None: ...
    @abstractmethod
    def next_id(self) -> str: ...


class ParentLinkRepository(ABC):
    @abstractmethod
    def student_ids_for_parent(self, parent_id: str) -> set[str]: ...
    @abstractmethod
    def link(self, parent_id: str, student_id: str) -> None: ...
    @abstractmethod
    def next_id(self) -> str: ...
