from abc import ABC, abstractmethod

from app.contexts.performance.domain.match import Match


class MatchRepository(ABC):
    @abstractmethod
    def add(self, match: Match) -> None: ...
    @abstractmethod
    def save(self, match: Match) -> None: ...
    @abstractmethod
    def get(self, match_id: str) -> Match | None: ...
    @abstractmethod
    def list_by_school(self, school_id: str) -> list[Match]: ...
    @abstractmethod
    def remove(self, match: Match) -> None: ...
    @abstractmethod
    def next_id(self) -> str: ...
    @abstractmethod
    def next_stat_id(self) -> str: ...
