from abc import ABC, abstractmethod

from app.contexts.school.domain.school_class import SchoolClass
from app.contexts.school.domain.enrollment import Enrollment


class ClassRepository(ABC):
    @abstractmethod
    def add(self, school_class: SchoolClass) -> None: ...
    @abstractmethod
    def get(self, class_id: str) -> SchoolClass | None: ...
    @abstractmethod
    def list_by_school(self, school_id: str) -> list[SchoolClass]: ...
    @abstractmethod
    def remove(self, school_class: SchoolClass) -> None: ...
    @abstractmethod
    def active_student_ids(self, class_id: str) -> list[str]: ...
    @abstractmethod
    def next_id(self) -> str: ...


class EnrollmentRepository(ABC):
    @abstractmethod
    def find(self, class_id: str, student_id: str) -> Enrollment | None: ...
    @abstractmethod
    def create(self, id: str, class_id: str, student_id: str) -> None: ...
    @abstractmethod
    def set_active(self, class_id: str, student_id: str, active: bool) -> None: ...
    @abstractmethod
    def next_id(self) -> str: ...


class StudentLookup(ABC):
    @abstractmethod
    def belongs_to_school(self, student_id: str, school_id: str) -> bool: ...
