from abc import ABC, abstractmethod

from app.contexts.billing.domain.payment import Payment


class PaymentRepository(ABC):
    @abstractmethod
    def add(self, payment: Payment) -> None: ...
    @abstractmethod
    def save(self, payment: Payment) -> None: ...
    @abstractmethod
    def get(self, payment_id: str) -> Payment | None: ...
    @abstractmethod
    def list_by_school(self, school_id: str, month_key: str | None = None,
                       student_id: str | None = None) -> list[Payment]: ...
    @abstractmethod
    def list_by_student(self, student_id: str) -> list[Payment]: ...
    @abstractmethod
    def remove(self, payment: Payment) -> None: ...
    @abstractmethod
    def student_belongs_to_school(self, student_id: str, school_id: str) -> bool: ...
    @abstractmethod
    def exists_for_student_month(self, student_id: str, month_key: str) -> bool: ...
    @abstractmethod
    def next_id(self) -> str: ...
