from abc import ABC, abstractmethod

from app.contexts.reporting.domain.read_models import StudentRef, EvalSnapshot


class ReportingRepository(ABC):
    """Porta de leitura (read model) que atravessa vários contextos.

    A implementação consulta o ORM diretamente; a composição das views
    (radar, deltas, médias) fica nos casos de uso da camada de aplicação.
    """

    @abstractmethod
    def get_student(self, student_id: str) -> StudentRef | None: ...
    @abstractmethod
    def class_info(self, student_id: str) -> tuple[str | None, str | None]: ...
    @abstractmethod
    def evaluations_desc(self, student_id: str) -> list[EvalSnapshot]: ...
    @abstractmethod
    def latest_axes(self, student_id: str) -> list[float | None] | None: ...
    @abstractmethod
    def attendance_summary(self, student_id: str) -> dict: ...
    @abstractmethod
    def match_summary(self, student_id: str) -> dict: ...
    @abstractmethod
    def class_peer_ids(self, school_id: str, class_name: str) -> set[str]: ...
    @abstractmethod
    def category_peer_ids(self, school_id: str, category: str) -> set[str]: ...
    @abstractmethod
    def school_overview(self, school_id: str) -> dict: ...
    @abstractmethod
    def top_scorers(self, school_id: str, limit: int = 5) -> list[dict]: ...
