from abc import ABC, abstractmethod

from app.contexts.assessment.domain.evaluation import Evaluation


class EvaluationRepository(ABC):
    @abstractmethod
    def add(self, evaluation: Evaluation) -> None: ...
    @abstractmethod
    def get(self, evaluation_id: str) -> Evaluation | None: ...
    @abstractmethod
    def list_by_school(self, school_id: str, student_id: str | None = None) -> list[Evaluation]: ...
    @abstractmethod
    def list_by_student(self, student_id: str) -> list[Evaluation]: ...
    @abstractmethod
    def remove(self, evaluation: Evaluation) -> None: ...
    @abstractmethod
    def student_belongs_to_school(self, student_id: str, school_id: str) -> bool: ...
    @abstractmethod
    def next_id(self) -> str: ...
