from abc import ABC, abstractmethod

from app.contexts.attendance.domain.session import AttendanceSession


class AttendanceRepository(ABC):
    @abstractmethod
    def add(self, session: AttendanceSession) -> None: ...
    @abstractmethod
    def get(self, session_id: str) -> AttendanceSession | None: ...
    @abstractmethod
    def list_by_school(self, school_id: str, class_id: str | None = None) -> list[AttendanceSession]: ...
    @abstractmethod
    def list_by_student(self, student_id: str) -> list[AttendanceSession]: ...
    @abstractmethod
    def remove(self, session: AttendanceSession) -> None: ...
    @abstractmethod
    def class_belongs_to_school(self, class_id: str, school_id: str) -> bool: ...
    @abstractmethod
    def students_all_in_school(self, student_ids: set[str], school_id: str) -> bool: ...
    @abstractmethod
    def next_id(self) -> str: ...
    @abstractmethod
    def next_record_id(self) -> str: ...
